Cross platform file picker
SkyLabs-Innovation-Group/SkyDrop pull request #32
Opened 2021-03-27 03:46 UTC by wellhat

2021-03-28 02:30 UTC, tomShoutTheSecond requested changes
Two issues I found on this branch

1. Animation glitch: AnimateSlideSendButton should be called immediately after the user selects a file (ie. before the upload starts)
2. Choosing "Select Image" takes me to Android's file browser instead of my default gallery app

2021-04-04 16:36 UTC, wellhat commented
Updated @tomShoutTheSecond

2021-04-04 16:57 UTC, tomShoutTheSecond commented on src/SkyDrop.Core/ViewModels/DropViewModel.cs
> +                using (var stream = await firstFile.OpenReadAsync())
NullReferenceException thrown here when user presses hardware back button while browsing for a file

2021-04-04 17:02 UTC, tomShoutTheSecond commented
Slide animation glitchy

https://user-images.githubusercontent.com/42177014/113516011-e2911700-956f-11eb-9096-993356c73518.mp4

2021-04-04 17:18 UTC, tomShoutTheSecond commented
Bug: send file button does not work while the barcode is loading (might also be an issue on main branch)

2021-04-12 19:30 UTC, merged